allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  sharp: true
  workerd: true

patchedDependencies:
  beasties: patches/beasties.patch
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
