name: Deploy on push

concurrency:
  group: deploy
  cancel-in-progress: true

on:
  push:
    branches:
      - develop
      - main

env:
  CLOUDFLARE_ACCOUNT_ID: 1a5d304db1c315f0731d67e097a1ee6c
  PAGES_PROJECT_NAME: vcpkg

jobs:
  deploy:
    name: Build and deploy

    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Check data
        run: pnpm run validate:sync

      - name: Check codes
        run: |
          pnpm run lint
          pnpm run typecheck

      - name: Generate social media images (OGP)
        run: pnpm run generate:images

      - name: Set expires header
        run: echo "VP_ENABLE_EXPIRES_HEADER=1" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: cloudflare/pages-action@v1
        with:
          directory: dist
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.PAGES_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
