name: Deploy preview

concurrency:
  group: preview
  cancel-in-progress: true

on:
  push:
    branches:
      - develop

env:
  CLOUDFLARE_ACCOUNT_ID: 1a5d304db1c315f0731d67e097a1ee6c
  PAGES_PROJECT_NAME: vcpkg

jobs:
  deploy:
    name: Build and deploy

    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - run: pnpm i --frozen-lockfile

      - name: Check data
        run: pnpm run validate:sync

      - name: Check codes
        run: |
          pnpm run lint
          pnpm run typecheck

      - run: pnpm run generate:images

      - run: pnpm run build

      - name: Deploy
        uses: cloudflare/pages-action@1
        with:
          directory: dist
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.PAGES_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
